name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 3107
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Create schema
      run: |
        PGPASSWORD=3107 psql -h localhost -U postgres -d postgres -f internal/database/schema.sql
      env:
        PGHOST: localhost
        PGPORT: 5432

    - name: Run unit tests
      run: go test ./internal/... -v
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 3107
        DB_NAME: postgres

    - name: Build and start application
      run: |
        go build -o swift-parser cmd/db/init.go
        ./swift-parser &
        sleep 15  # Give more time for app to start
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 3107
        DB_NAME: postgres

    - name: Run integration tests
      run: go test ./tests/integration/... -v -count=1
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 3107
        DB_NAME: postgres

    - name: Check logs if tests fail
      if: failure()
      run: |
        ps aux | grep swift-parser
        tail -n 50 /tmp/swift-parser.log