name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 3107
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Initialize Database
      run: |
        # Drop existing tables if they exist
        PGPASSWORD=3107 psql -h localhost -U postgres -d postgres -c "DROP TABLE IF EXISTS swift_codes CASCADE;"
        
        # Create schema
        PGPASSWORD=3107 psql -h localhost -U postgres -d postgres -f internal/database/schema.sql
        
        # Insert test data
        PGPASSWORD=3107 psql -h localhost -U postgres -d postgres -c "
          INSERT INTO swift_codes (swift_code, country_iso2, country_name, bank_name, address, is_headquarter)
          VALUES 
            ('ANIBAWA1XXX', 'TR', 'TURKEY', 'TEST BANK HQ', 'TEST ADDRESS 123', true),
            ('BCHICLR10R2', 'TR', 'TURKEY', 'TEST BANK BRANCH', 'BRANCH ADDRESS 456', false)
          ON CONFLICT DO NOTHING;"
      env:
        PGHOST: localhost
        PGPORT: 5432

    - name: Run tests
      run: go test ./... -v
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 3107
        DB_NAME: postgres